import{qs,download,escapeHtml}from'./ui.js';import{activeProject}from'./storage.js';
let componentData=[];
export function initExport(state,dangers,components=[]){componentData=components;qs('#exportJsonBtn').onclick=()=>download('ce-projekt.json',JSON.stringify(activeProject(state),null,2),'application/json');qs('#exportCsvBtn').onclick=()=>{if(validate(state,dangers))exportCsv(state,dangers)};qs('#exportWordBtn').onclick=()=>{if(validate(state,dangers))exportWord(state,dangers)};qs('#printReportBtn').onclick=()=>{if(validate(state,dangers))window.print()}}
function relevant(p,dangers){if(!p)return[];if(p.machineType==='sondermaschine')return dangers.filter(d=>!(p.excludedRiskGroups||[]).includes(d.gruppe));let list=dangers.filter(d=>!p.machineType||d.maschinen.includes(p.machineType));const hidden=new Set();for(const c of componentData){if(p.components?.[c.id]==='no')(c.groups||[]).forEach(g=>hidden.add(g))}for(const g of [...hidden]){const rel=componentData.filter(c=>(c.groups||[]).includes(g));if(rel.some(c=>p.components?.[c.id]!=='no'))hidden.delete(g)}return list.filter(d=>!hidden.has(d.gruppe)&&!(p.excludedRiskGroups||[]).includes(d.gruppe))}
function complete(r){if(r.answer==='no')return true;if(r.answer!=='yes')return false;return Boolean(r.severity&&r.frequency&&r.possibility&&(r.measure||'').trim()&&r.residualSeverity&&r.residualFrequency&&r.residualPossibility)}
function validate(state,dangers){const p=activeProject(state);if(!p){alert('Bitte zuerst ein Projekt auswählen.');return false}const rel=relevant(p,dangers);const missing=rel.filter(d=>!complete(p.risk?.[d.id]||{}));if(missing.length){alert(`Export gesperrt: ${missing.length} relevante Gefährdungsbewertungen sind noch unvollständig. Verwenden Sie den Filter „Unvollständig“. JSON-Sicherungen sind weiterhin möglich.`);return false}return true}
function rows(state,dangers){const p=activeProject(state);return relevant(p,dangers).map(d=>{const r=p.risk?.[d.id]||{};return[d.id,d.gruppe,d.untergruppe,d.bereich,d.frage,r.answer||'',r.description||'',r.severity||'',r.frequency||'',r.possibility||'',r.measure||'',r.residualSeverity||'',r.residualFrequency||'',r.residualPossibility||'',r.residualRisk||'',(d.normen||[]).join('; ')]})}
function exportCsv(state,dangers){const data=[['ID','Gruppe','Untergruppe','Bereich','Frage','Antwort','Beschreibung','S','F','P','Maßnahme','Rest-S','Rest-F','Rest-P','Restrisiko','Normen'],...rows(state,dangers)];download('risikoanalyse.csv','\ufeff'+data.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(';')).join('\n'),'text/csv;charset=utf-8')}
function exportWord(state,dangers){const p=activeProject(state);const body=`<html><head><meta charset="utf-8"><style>body{font-family:Arial}table{border-collapse:collapse;width:100%}td,th{border:1px solid #999;padding:6px;font-size:9pt}h1{color:#60993b}</style></head><body><h1>Risikobeurteilung</h1><p><b>Projekt:</b> ${escapeHtml(p.projectNo||'')} – ${escapeHtml(p.projectName||'')}</p><p><b>Kunde:</b> ${escapeHtml(p.customer||'')}</p><table><thead><tr><th>ID</th><th>Gefährdung</th><th>Antwort</th><th>S/F/P</th><th>Maßnahme</th><th>Rest-S/F/P</th><th>Restrisiko</th></tr></thead><tbody>${rows(state,dangers).map(r=>`<tr><td>${escapeHtml(r[0])}</td><td>${escapeHtml(r[4])}</td><td>${escapeHtml(r[5])}</td><td>${escapeHtml([r[7],r[8],r[9]].join('/'))}</td><td>${escapeHtml(r[10])}</td><td>${escapeHtml([r[11],r[12],r[13]].join('/'))}</td><td>${escapeHtml(r[14])}</td></tr>`).join('')}</tbody></table></body></html>`;download('risikobeurteilung.doc',body,'application/msword')}
